name: Build iSH-Compatible Debian Rootfs

on:
  push:
    branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up workspace
      run: mkdir rootfs

    - name: Install debootstrap
      run: sudo apt-get update && sudo apt-get install -y debootstrap

    - name: Build Debian i386 Rootfs with bash + libs
      run: |
        sudo debootstrap \
          --arch=i386 \
          --variant=minbase \
          --include=bash,libtinfo6,libc6 \
          bullseye rootfs http://deb.debian.org/debian

        sudo rm -rf rootfs/usr/share/{doc,locale,man,info}
        echo "nameserver 1.1.1.1" | sudo tee rootfs/etc/resolv.conf
        sudo tar -czf ish-debian-bash.tar.gz -C rootfs .

    - name: Upload rootfs artifact
      uses: actions/upload-artifact@v4
      with:
        name: ish-debian-bash
        path: ish-debian-bash.tar.gz
